### ISSUE TITLE
failed to import extension hggit: No module named hggit

### ISSUE THREAD

**Issue by quantonganh** [quantonganh/salt-osx#7]
```
----------
          ID: tig
    Function: pkg.installed
      Result: False
     Comment: Brew command failed. Additional info follows:

              result:
                  ----------
                  pid:
                      50601
                  retcode:
                      1
                  stderr:
                      *** failed to import extension hggit: No module named hggit
                      Error: undefined method `undent' for #<String:0x00007fb08bc826a0>
                      Please report this issue:
                        https://docs.brew.sh/Troubleshooting
                      /usr/local/opt/wine/.brew/wine.rb:464:in `caveats'
                      /usr/local/Homebrew/Library/Homebrew/formula.rb:1684:in `to_hash'
                      /usr/local/Homebrew/Library/Homebrew/cmd/info.rb:141:in `map'
                      /usr/local/Homebrew/Library/Homebrew/cmd/info.rb:141:in `print_json'
                      /usr/local/Homebrew/Library/Homebrew/cmd/info.rb:86:in `info'
                      /usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by quantonganh** [comment]
```
$ /usr/local/bin/hg -h
*** failed to import extension hggit: No module named 'hggit'
Mercurial Distributed SCM
```

**Comment by quantonganh** [comment]
```
$ head /usr/local/bin/hg
#!/usr/local/opt/python/bin/python3.7

$ /usr/local/opt/python/bin/pip3 install hg-git

$ /usr/local/opt/python/bin/python3.7 -c "import hggit"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/hggit/__init__.py", line 24, in <module>
    import compat
ModuleNotFoundError: No module named 'compat'
```
